language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -L https://unpkg.com/@pnpm/self-installer | node
node_js:
  - "node"
  - "lts/*"
  - "lts/carbon"
cache: yarn
notifications:
  email: false
